# Generated by Django 5.2.5 on 2025-09-03 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pond',
            fields=[
                ('pond_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('weather_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Pond',
                'verbose_name_plural': 'Ponds',
                'db_table': 'pond',
            },
        ),
        migrations.CreateModel(
            name='PondSection',
            fields=[
                ('pond_section_id', models.AutoField(primary_key=True, serialize=False)),
                ('pond_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gameplay.pond')),
            ],
            options={
                'verbose_name': 'Pond Section',
                'verbose_name_plural': 'Pond Sections',
                'db_table': 'pond_section',
            },
        ),
        migrations.CreateModel(
            name='SpawnPoint',
            fields=[
                ('spawn_point_id', models.AutoField(primary_key=True, serialize=False)),
                ('pond_section_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gameplay.pondsection')),
            ],
            options={
                'verbose_name': 'Spawn Point',
                'verbose_name_plural': 'Spawn Points',
                'db_table': 'spawn_point',
            },
        ),
        migrations.CreateModel(
            name='SpawnPointFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_placed', models.DateTimeField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='catalog.food')),
                ('spawn_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filled_spawn_point', to='gameplay.spawnpoint')),
            ],
            options={
                'db_table': 'spawn_point_food',
                'constraints': [models.UniqueConstraint(fields=('spawn_point', 'food'), name='unique_spawn_point_food')],
            },
        ),
    ]
