# Generated by Django 5.2.5 on 2025-09-04 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_duck_spawn_point'),
        ('gameplay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spawnpoint',
            name='duck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spawn_points', to='catalog.duck'),
        ),
    ]
