# Generated by Django 5.2.5 on 2025-09-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duck',
            fields=[
                ('duck_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('rarity', models.IntegerField()),
                ('favorite_food', models.CharField(max_length=100)),
                ('duck_energy', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Duck',
                'verbose_name_plural': 'Ducks',
                'db_table': 'ducks',
            },
        ),
        migrations.CreateModel(
            name='DuckFlavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_value', models.IntegerField()),
            ],
            options={
                'db_table': 'duck_flavor',
            },
        ),
        migrations.CreateModel(
            name='DuckToy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_value', models.IntegerField()),
            ],
            options={
                'db_table': 'duck_toy',
            },
        ),
        migrations.CreateModel(
            name='DuckWaterTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_value', models.IntegerField()),
            ],
            options={
                'db_table': 'duck_water_temp',
            },
        ),
        migrations.CreateModel(
            name='DuckWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_value', models.IntegerField()),
            ],
            options={
                'db_table': 'duck_weather',
            },
        ),
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('flavor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Flavor',
                'verbose_name_plural': 'Flavors',
                'db_table': 'flavor',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Food',
                'verbose_name_plural': 'Foods',
                'db_table': 'food',
            },
        ),
        migrations.CreateModel(
            name='FoodFlavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField()),
            ],
            options={
                'db_table': 'food_flavor',
            },
        ),
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('toy_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Toy',
                'verbose_name_plural': 'Toys',
                'db_table': 'toy',
            },
        ),
        migrations.CreateModel(
            name='WaterTemperature',
            fields=[
                ('temp_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Water Temperature',
                'verbose_name_plural': 'Water Temperatures',
                'db_table': 'water_temperature',
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('weather_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Weather',
                'verbose_name_plural': 'Weathers',
                'db_table': 'weather',
            },
        ),
    ]
