# Generated by Django 5.2.5 on 2025-09-03 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('gameplay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='duck',
            name='spawn_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gameplay.spawnpoint'),
        ),
        migrations.AddField(
            model_name='duckflavor',
            name='duck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flavor_preferences', to='catalog.duck'),
        ),
        migrations.AddField(
            model_name='ducktoy',
            name='duck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toy_preferences', to='catalog.duck'),
        ),
        migrations.AddField(
            model_name='duckwatertemp',
            name='duck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_temp_preferences', to='catalog.duck'),
        ),
        migrations.AddField(
            model_name='duckweather',
            name='duck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_preferences', to='catalog.duck'),
        ),
        migrations.AddField(
            model_name='duckflavor',
            name='flavor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ducks', to='catalog.flavor'),
        ),
        migrations.AddField(
            model_name='duck',
            name='flavors',
            field=models.ManyToManyField(through='catalog.DuckFlavor', to='catalog.flavor'),
        ),
        migrations.AddField(
            model_name='foodflavor',
            name='flavor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flavors', to='catalog.flavor'),
        ),
        migrations.AddField(
            model_name='foodflavor',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='catalog.food'),
        ),
        migrations.AddField(
            model_name='food',
            name='flavors',
            field=models.ManyToManyField(through='catalog.FoodFlavor', to='catalog.flavor'),
        ),
        migrations.AddField(
            model_name='toy',
            name='pond_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gameplay.pondsection'),
        ),
        migrations.AddField(
            model_name='ducktoy',
            name='toy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ducks', to='catalog.toy'),
        ),
        migrations.AddField(
            model_name='duck',
            name='toy',
            field=models.ManyToManyField(through='catalog.DuckToy', to='catalog.toy'),
        ),
        migrations.AddField(
            model_name='watertemperature',
            name='pond_section',
            field=models.ManyToManyField(to='gameplay.pondsection'),
        ),
        migrations.AddField(
            model_name='duckwatertemp',
            name='water_temp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ducks', to='catalog.watertemperature'),
        ),
        migrations.AddField(
            model_name='duck',
            name='water_temp',
            field=models.ManyToManyField(through='catalog.DuckWaterTemp', to='catalog.watertemperature'),
        ),
        migrations.AddField(
            model_name='duckweather',
            name='weather',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ducks', to='catalog.weather'),
        ),
        migrations.AddField(
            model_name='duck',
            name='weather',
            field=models.ManyToManyField(through='catalog.DuckWeather', to='catalog.weather'),
        ),
        migrations.AddConstraint(
            model_name='duckflavor',
            constraint=models.UniqueConstraint(fields=('duck', 'flavor'), name='unique_duck_flavor'),
        ),
        migrations.AddConstraint(
            model_name='foodflavor',
            constraint=models.UniqueConstraint(fields=('food', 'flavor'), name='unique_food_flavor'),
        ),
        migrations.AddConstraint(
            model_name='ducktoy',
            constraint=models.UniqueConstraint(fields=('duck', 'toy'), name='unique_duck_toy'),
        ),
        migrations.AddConstraint(
            model_name='duckwatertemp',
            constraint=models.UniqueConstraint(fields=('duck', 'water_temp'), name='unique_duck_water_temp'),
        ),
        migrations.AddConstraint(
            model_name='duckweather',
            constraint=models.UniqueConstraint(fields=('duck', 'weather'), name='unique_duck_weather'),
        ),
    ]
