# Generated by Django 5.2.5 on 2025-09-04 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duck',
            name='spawn_point',
        ),
    ]
